name: Test deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        run : actions/checkout@3 
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run Test
      - name: Build code
        run: npm run Build
      - name: Deploy project
        run: echo "Deploy finish"
